---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-share
  namespace: default
data:
  index.html: |
    Hello World!

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: share-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: share-files
        configMap:
          name: nginx-share
          items:
          - key: index.html
            path: index.html

---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
